### ISSUE TITLE
Shrink Public API Surface for 1.0 (Umbrella Ticket)

### ISSUE THREAD

**Issue by jenshalm** [typelevel/Laika#452]
The major (or even sole) focus for `1.0.0-M2` will be to dramatically shrink the public API surface to ensure longterm binary-compatibility is feasible for the 1.x lifespan. 

Many APIs are public "by accident", since it is the default access and earlier years did not put a major emphasis on bincompat anyway (it was an unrealistic goal as long as very large new sets of functionality were introduced). By now Laika has matured in a way that it makes sense to address these historic issues now.

The main public APIs that need to remain are:

* The core APIs to configure and run a transformation.
* The main extension APIs (everything reachable from the `ExtensionBundle` type).
* The theme support and Helium configuration and types reachable from there.
* The APIs of the included micro-libs, mainly parser combinators and config/hocon support.
* The API entry point to launch a preview server.
* The keys for settings and tasks in the sbt plugin as well as relevant helpers.

For everything else package-private should become the new default.

This will most likely leave behind some skeleton packages with only a few public types left. These will be "re-homed" later, but renaming and repackaging in general is left for the final milestone to keep the 0.19 maintenance branch largely in sync as long as possible.

To avoid a mega-PR the work will be split into the following sub-tasks (PRs will be linked here as soon as they are created):

- [x] **Core APIs & Utilities** - #457
    packages `laika.api`, `laika.ast`, `laika.format`, `laika.factory`, `laika.time`, `laika.collection`
- [x] **Core Extension Points** - #462
    packages `laika.bundle`, `laika.directive`, `laika.parse.directive`
- [x] **Hocon Config** - #463
    packages `laika.config`, `laika.parse.hocon`
- [x] **Parser Library** - #473
    packages `laika.parse`, `laika.parse.combinator`, `laika.parse.text`, `laika.parse.markup`
- [x] **Core Internal Runtime** - #474
    package `laika.rewrite`, `laika.render`
- [x] **Markup Parsers - Markdown & reStrucutredText** - #475
    packages `laika.markdown`, `laika.rst`
- [x] **Other Parser Implementations** - #469
    packages `laika.parse.code`, `laika.parse.css`, `laika.parse.uri`
- [x] **`laika-io` User APIs & Runtime** - #465
    package `laika.io`
- [x] **Theme Support & Helium Config** - #466
    packages `laika.helium`, `laika.theme`
- [x] **EPUB & PDF Renderer**  - #468
    packages `laika.render.epub`, `laika.render.pdf`
- [x] **Sbt Plugin & Preview Server** - #467
    packages `laika.sbt`, `laika.preview`
